"""Markdown report renderer."""
from __future__ import annotations

from datetime import datetime, timezone

from didileak.models import ScanResult, Severity
from didileak.reporters.redact import mask_pairs, redact_context

SEVERITY_BADGE = {
    Severity.CRITICAL: "[CRITICAL]",
    Severity.HIGH: "[HIGH]",
    Severity.MEDIUM: "[MEDIUM]",
    Severity.LOW: "[LOW]",
    Severity.INFO: "[INFO]",
}


def _fmt_ts(ts: float | None) -> str:
    if ts is None:
        return "unknown"
    try:
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    except (OSError, ValueError):
        return "unknown"


def render_markdown(result: ScanResult) -> str:
    """Render a human-readable Markdown triage report."""
    out: list[str] = []
    by_sev = result.by_severity()
    total = result.total_findings

    out.append("# didileak report\n")
    out.append(f"_Generated: {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}_\n")
    out.append(f"**Source:** `{result.source}`  ")
    out.append(f"**Provider:** {result.provider}  ")
    out.append(f"**Messages scanned:** {result.messages_scanned}  ")
    out.append(f"**Conversations scanned:** {result.conversations_scanned}\n")

    # Triage summary
    out.append("## Triage summary\n")
    out.append("| Severity | Count |")
    out.append("|---|---|")
    for sev in Severity:
        out.append(f"| {sev.value} | {by_sev.get(sev.value, 0)} |")
    out.append(f"| **TOTAL** | **{total}** |\n")

    if total == 0:
        out.append("No secrets or PII detected. Stay vigilant -- new detectors ship monthly.\n")
        if result.parser_warnings:
            out.append("## Parser warnings\n")
            for w in result.parser_warnings:
                out.append(f"- {w}")
            out.append("")
        out.append("---")
        out.append("_Generated by [DidILeak](https://github.com/frangelbarrera/DidILeak) — "
                   "OSINT-BIBLE taught you to investigate others. DidILeak teaches you to investigate yourself._")
        return "\n".join(out)

    # Category breakdown
    out.append("## By category\n")
    out.append("| Category | Findings |")
    out.append("|---|---|")
    for cat, n in sorted(result.by_category().items(), key=lambda x: -x[1]):
        out.append(f"| {cat} | {n} |")
    out.append("")

    # Rule breakdown
    out.append("## By detector\n")
    out.append("| Rule | Count |")
    out.append("|---|---|")
    for rule, n in sorted(result.by_rule().items(), key=lambda x: -x[1]):
        out.append(f"| `{rule}` | {n} |")
    out.append("")

    # Findings
    out.append("## Findings\n")
    out.append("> Values are masked. Keep full values for incident response with "
               "`didileak scan <export> --json report.json` (or `didileak report <export> "
               "--outdir <dir>`); treat the JSON file as a secret.\n")

    # Redact globally: a context window can contain the full secret of ANOTHER
    # finding when matches overlap, and titles may embed secrets too.
    pairs = mask_pairs(result.findings)
    for i, f in enumerate(result.sorted_findings(), 1):
        title = redact_context(f.conversation_title, pairs)
        out.append(f"### {i}. {SEVERITY_BADGE[f.severity]} {f.rule_name}")
        out.append(f"- **Rule:** `{f.rule_id}`")
        out.append(f"- **Matched value:** `{f.masked_value}`")
        out.append(f"- **Conversation:** {title or '(unknown)'}")
        out.append(f"- **Role:** {redact_context(f.role, pairs)}")
        out.append(f"- **Timestamp:** {_fmt_ts(f.timestamp)}")
        out.append("- **Context:**")
        out.append(f"  > {redact_context(f.context, pairs)}")
        if f.rotation_guide:
            out.append(f"- **Rotation guide:** {f.rotation_guide}")
        out.append("")

    if result.parser_warnings:
        out.append("## Parser warnings\n")
        for w in result.parser_warnings:
            out.append(f"- {w}")
        out.append("")

    out.append("---")
    out.append("_Generated by [DidILeak](https://github.com/frangelbarrera/DidILeak) — "
               "OSINT-BIBLE taught you to investigate others. DidILeak teaches you to investigate yourself._")
    return "\n".join(out)
